#importamos la imagen base con python
FROM python:3.12-slim

#Creamos carpeta de trabajo del contenedor
WORKDIR /app

#Copiamos los requerimientos del servidor
COPY requirements.txt .

#Instalamos los requerimientos
RUN pip install --no-cache-dir -r requirements.txt

#copiar el codigo del API
COPY ./app ./app

#exponer el puerto
EXPOSE 5000

#comado de ejecucion FASTAPI
CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","5000","--reload"]